# Generated by Django 5.2.15 on 2026-06-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_use_parking',
            field=models.BooleanField(default=True, verbose_name='Pode usar estacionamento'),
        ),
    ]
