# Generated by Django 5.2.15 on 2026-06-13 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='Data da reserva')),
                ('period', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('full_day', 'Dia inteiro')], max_length=10, verbose_name='Período')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('cancelled', 'Cancelada'), ('finished', 'Finalizada')], default='active', max_length=10, verbose_name='Status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parking_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='parking.parkingspot', verbose_name='Vaga de estacionamento')),
                ('room_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.roomposition', verbose_name='Posição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'indexes': [models.Index(fields=['reservation_date', 'period', 'status'], name='booking_res_reserva_20dfc6_idx'), models.Index(fields=['room_position'], name='booking_res_room_po_73ff14_idx'), models.Index(fields=['parking_spot'], name='booking_res_parking_9ed241_idx'), models.Index(fields=['user'], name='booking_res_user_id_99dc2f_idx')],
            },
        ),
    ]
