# Generated by Django 5.2.15 on 2026-06-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('type', models.CharField(choices=[('common', 'Comum'), ('accessible', 'Acessível'), ('visitor', 'Visitante'), ('reserved', 'Reservada')], default='common', max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('blocked', 'Bloqueada'), ('inactive', 'Inativa')], default='available', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaga de estacionamento',
                'verbose_name_plural': 'Vagas de estacionamento',
            },
        ),
    ]
