# Generated by Django 5.2.15 on 2026-06-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinatário')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('email_type', models.CharField(choices=[('access_invitation', 'Convite de acesso'), ('password_reset', 'Redefinição de senha'), ('reservation_confirmation', 'Confirmação de reserva'), ('reservation_cancelled', 'Cancelamento de reserva'), ('smtp_test', 'Teste SMTP')], max_length=30, verbose_name='Tipo de e-mail')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('pending', 'Pendente')], max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de e-mail',
                'verbose_name_plural': 'Registros de e-mails',
            },
        ),
    ]
