# Generated by Django 5.2.15 on 2026-06-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('access_invitation', 'Convite de acesso'), ('password_reset', 'Redefinição de senha'), ('reservation_confirmation', 'Confirmação de reserva'), ('reservation_cancelled', 'Cancelamento de reserva'), ('smtp_test', 'Teste SMTP'), ('welcome_credentials', 'Credenciais de boas-vindas')], max_length=30, verbose_name='Tipo de e-mail'),
        ),
    ]
