# Generated by Django 5.2.15 on 2026-06-13 05:29

import system_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Sistema de Reservas', max_length=100, verbose_name='Nome da aplicação')),
                ('app_base_url', models.URLField(blank=True, verbose_name='URL base da aplicação')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[system_settings.models.validate_image], verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', validators=[system_settings.models.validate_image], verbose_name='Favicon')),
                ('login_image', models.ImageField(blank=True, null=True, upload_to='login/', validators=[system_settings.models.validate_image], verbose_name='Imagem de login')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor primária')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor secundária')),
                ('background_color', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Cor de fundo')),
                ('welcome_text', models.TextField(blank=True, default='Bem-vindo ao Sistema de Reservas', verbose_name='Texto de boas-vindas')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de suporte')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de suporte')),
                ('email_sender_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do remetente')),
                ('email_sender_address', models.EmailField(blank=True, max_length=254, verbose_name='E-mail remetente')),
                ('email_reply_to', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de resposta')),
                ('smtp_host', models.CharField(blank=True, max_length=200, verbose_name='Host SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_username', models.CharField(blank=True, max_length=200, verbose_name='Usuário SMTP')),
                ('smtp_password_encrypted', models.TextField(blank=True, verbose_name='Senha SMTP (criptografada)')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_settings_active', models.BooleanField(default=False, verbose_name='Configuração de e-mail ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
    ]
