# Generated by Django 5.2.15 on 2026-06-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='navbar_bg_color',
            field=models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor da barra de navegação'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='navbar_text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do texto da barra de navegação'),
        ),
    ]
