# Generated by Django 5.2.15 on 2026-06-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_systemsettings_navbar_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da organização'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='send_cancellation_email',
            field=models.BooleanField(default=True, verbose_name='Enviar e-mail ao cancelar reserva'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='send_confirmation_email',
            field=models.BooleanField(default=True, verbose_name='Enviar e-mail ao confirmar reserva'),
        ),
    ]
