# Generated by Django 5.2.15 on 2026-06-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0003_systemsettings_organization_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='support_phone',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_app_name_footer',
            field=models.BooleanField(default=True, verbose_name='Exibir nome no rodapé'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_app_name_login',
            field=models.BooleanField(default=True, verbose_name='Exibir nome na tela de login'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_app_name_navbar',
            field=models.BooleanField(default=True, verbose_name='Exibir nome na barra de navegação'),
        ),
    ]
