# Generated by Django 5.2.15 on 2026-06-15 04:07

import system_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_remove_systemsettings_support_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='background_color',
            field=models.CharField(default='#f8f9fa', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor de fundo'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='navbar_bg_color',
            field=models.CharField(default='#0d6efd', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor da barra de navegação'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='navbar_text_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor do texto da barra de navegação'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor primária'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor secundária'),
        ),
    ]
