# Generated by Django 5.2.15 on 2026-06-15 16:27

import system_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_update_color_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='use_offcanvas_nav',
            field=models.BooleanField(default=True, verbose_name='Usar menu offcanvas no celular'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='background_color',
            field=models.CharField(default='#f8fafc', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor de fundo'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='navbar_bg_color',
            field=models.CharField(default='#4f46e5', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor da barra de navegação'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#4f46e5', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor primária'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='secondary_color',
            field=models.CharField(default='#f43f5e', max_length=7, validators=[system_settings.models.validate_hex_color], verbose_name='Cor secundária'),
        ),
    ]
